from .base import CRUDBase
from .user import user
from .vehicle import vehicle
from .driver import driver
from .trip import trip
from .maintenance import maintenance
from .fuel_log import fuel_log
from .expense import expense
from .settings import settings
